/* This file is generated by scripts/generate-content.mjs. */
import type { ComponentType } from 'react';
import Article0Zh from './generated/articles/riboseek-fast-nucleotide-alignment.zh';
import Article0En from './generated/articles/riboseek-fast-nucleotide-alignment.en';

export const articleBodies: Record<string, Record<'zh' | 'en', ComponentType<Record<string, unknown>>>> = {
  "riboseek-fast-nucleotide-alignment": { zh: Article0Zh, en: Article0En },
};
