/* This file is generated by scripts/generate-content.mjs. */
import type { ArticleRecord, PaperRecord, TopicRecord } from './types';
export const articles = [
  {
    "slug": "beyond-structure-prediction",
    "date": "2026-08-20",
    "topics": [
      "foundation-models",
      "protein-structure"
    ],
    "papers": [
      "alphafold-3"
    ],
    "draft": false,
    "featured": true,
    "demo": true,
    "translations": {
      "zh": {
        "title": "超越结构预测：分子模型究竟学到了什么？",
        "summary": "从输入表示、生成目标和评估边界出发，拆解新一代分子模型真正捕获的生物学规律。",
        "readingMinutes": 12
      },
      "en": {
        "title": "Beyond structure prediction: what does a molecular model actually learn?",
        "summary": "A close reading of representation, generative objectives, and the biological limits of modern molecular models.",
        "readingMinutes": 12
      }
    },
    "toc": {
      "zh": [
        {
          "id": "从预测问题换一个角度",
          "title": "从预测问题换一个角度",
          "level": 2
        },
        {
          "id": "三个阅读问题",
          "title": "三个阅读问题",
          "level": 2
        },
        {
          "id": "1-表示里已经写入了什么",
          "title": "1. 表示里已经写入了什么？",
          "level": 3
        },
        {
          "id": "2-目标函数奖励了什么",
          "title": "2. 目标函数奖励了什么？",
          "level": 3
        },
        {
          "id": "3-失败发生在哪里",
          "title": "3. 失败发生在哪里？",
          "level": 3
        },
        {
          "id": "一张可复用的阅读清单",
          "title": "一张可复用的阅读清单",
          "level": 2
        }
      ],
      "en": [
        {
          "id": "reframing-the-prediction-problem",
          "title": "Reframing the prediction problem",
          "level": 2
        },
        {
          "id": "three-questions-for-a-close-reading",
          "title": "Three questions for a close reading",
          "level": 2
        },
        {
          "id": "1-what-is-already-encoded-in-the-representation",
          "title": "1. What is already encoded in the representation?",
          "level": 3
        },
        {
          "id": "2-what-does-the-objective-reward",
          "title": "2. What does the objective reward?",
          "level": 3
        },
        {
          "id": "3-where-does-failure-concentrate",
          "title": "3. Where does failure concentrate?",
          "level": 3
        },
        {
          "id": "a-reusable-reading-checklist",
          "title": "A reusable reading checklist",
          "level": 2
        }
      ]
    }
  },
  {
    "slug": "how-to-read-ai-bio-paper",
    "date": "2026-08-12",
    "topics": [
      "research-methods",
      "single-cell"
    ],
    "papers": [
      "scgpt"
    ],
    "draft": false,
    "featured": false,
    "demo": true,
    "translations": {
      "zh": {
        "title": "如何阅读一篇 AI × Bio 论文",
        "summary": "一套把机器学习指标还原成生物学问题的五步阅读框架。",
        "readingMinutes": 8
      },
      "en": {
        "title": "How to read an AI × Bio paper",
        "summary": "A five-step framework for translating machine-learning metrics back into biological questions.",
        "readingMinutes": 8
      }
    },
    "toc": {
      "zh": [
        {
          "id": "先找生物学问题",
          "title": "先找生物学问题",
          "level": 2
        },
        {
          "id": "再检查数据边界",
          "title": "再检查数据边界",
          "level": 2
        },
        {
          "id": "最后才看排行榜",
          "title": "最后才看排行榜",
          "level": 2
        }
      ],
      "en": [
        {
          "id": "start-with-the-biological-question",
          "title": "Start with the biological question",
          "level": 2
        },
        {
          "id": "inspect-the-data-boundary",
          "title": "Inspect the data boundary",
          "level": 2
        },
        {
          "id": "read-the-leaderboard-last",
          "title": "Read the leaderboard last",
          "level": 2
        }
      ]
    }
  },
  {
    "slug": "riboseek-fast-nucleotide-alignment",
    "date": "2026-07-31",
    "topics": [
      "nucleic-acids",
      "research-methods"
    ],
    "papers": [
      "riboseek"
    ],
    "draft": false,
    "featured": false,
    "demo": false,
    "translations": {
      "zh": {
        "title": "Riboseek：为 RNA 结构预测加速远缘同源搜索",
        "summary": "从重叠二联体到迭代搜索，解析 Riboseek 如何加速核酸 MSA 生成，以及搜索速度、同源检出能力与比对质量之间的权衡。",
        "readingMinutes": 14
      },
      "en": {
        "title": "Riboseek: accelerating remote homology search for RNA structure prediction",
        "summary": "How overlapping di-mers and iterative search help Riboseek generate nucleotide MSAs faster, and what its benchmarks reveal about speed, sensitivity, and alignment quality.",
        "readingMinutes": 14
      }
    },
    "toc": {
      "zh": [
        {
          "id": "rna-结构预测的瓶颈常常发生在模型之前",
          "title": "RNA 结构预测的瓶颈，常常发生在模型之前",
          "level": 2
        },
        {
          "id": "riboseek-的核心用二联体保留局部上下文",
          "title": "Riboseek 的核心：用二联体保留局部上下文",
          "level": 2
        },
        {
          "id": "如何把查询序列变成可搜索的-profile",
          "title": "如何把查询序列变成可搜索的 profile？",
          "level": 3
        },
        {
          "id": "riboseek-如何在数据库中搜索",
          "title": "Riboseek 如何在数据库中搜索？",
          "level": 3
        },
        {
          "id": "搜索有多灵敏生成的比对有多可靠",
          "title": "搜索有多灵敏，生成的比对有多可靠？",
          "level": 2
        },
        {
          "id": "1-远缘同源检出能力与搜索速度",
          "title": "1. 远缘同源检出能力与搜索速度",
          "level": 3
        },
        {
          "id": "2-msa-能否保留二级结构信号",
          "title": "2. MSA 能否保留二级结构信号？",
          "level": 3
        },
        {
          "id": "173-万份预计算-rna-msa",
          "title": "173 万份预计算 RNA MSA",
          "level": 2
        },
        {
          "id": "如何看待-riboseek-的贡献与局限",
          "title": "如何看待 Riboseek 的贡献与局限？",
          "level": 2
        }
      ],
      "en": [
        {
          "id": "the-bottleneck-often-comes-before-model-inference",
          "title": "The bottleneck often comes before model inference",
          "level": 2
        },
        {
          "id": "riboseeks-core-preserving-local-context-with-di-mers",
          "title": "Riboseek's core: preserving local context with di-mers",
          "level": 2
        },
        {
          "id": "how-does-a-query-become-a-searchable-profile",
          "title": "How does a query become a searchable profile?",
          "level": 3
        },
        {
          "id": "how-does-riboseek-search-a-database",
          "title": "How does Riboseek search a database?",
          "level": 3
        },
        {
          "id": "how-sensitive-is-the-search-and-how-reliable-are-the-alignments",
          "title": "How sensitive is the search, and how reliable are the alignments?",
          "level": 2
        },
        {
          "id": "1-remote-homology-detection-and-search-speed",
          "title": "1. Remote-homology detection and search speed",
          "level": 3
        },
        {
          "id": "2-do-the-msas-preserve-secondary-structure-signals",
          "title": "2. Do the MSAs preserve secondary-structure signals?",
          "level": 3
        },
        {
          "id": "173-million-precomputed-rna-msas",
          "title": "1.73 million precomputed RNA MSAs",
          "level": 2
        },
        {
          "id": "strengths-and-limitations",
          "title": "Strengths and limitations",
          "level": 2
        }
      ]
    }
  }
] satisfies ArticleRecord[];
export const papers = [
  {
    "slug": "riboseek",
    "originalTitle": "Fast remote nucleotide sequence alignment with Riboseek",
    "authors": [
      "Sukhwan Park",
      "Kieran Didi",
      "Andrew Favor",
      "Anton Bushuiev",
      "Soohyun Kim",
      "Milot Mirdita",
      "Martin Steinegger"
    ],
    "year": 2026,
    "venue": "bioRxiv",
    "doi": "10.64898/2026.07.31.741718",
    "url": "https://www.biorxiv.org/content/10.64898/2026.07.31.741718v1.full",
    "arxiv": null,
    "topics": [
      "nucleic-acids",
      "research-methods"
    ],
    "articles": [
      "riboseek-fast-nucleotide-alignment"
    ],
    "demo": false,
    "summaries": {
      "zh": "Riboseek 用重叠二联体、快速预筛选和迭代 profile search 加速 RNA 与 DNA 的远缘同源搜索，并为 RNA 结构预测生成更深的多序列比对。",
      "en": "Riboseek accelerates remote homology search for RNA and DNA with overlapping di-mers, fast prefiltering, and iterative profile search, generating deeper MSAs for RNA structure prediction."
    }
  },
  {
    "slug": "alphafold-3",
    "originalTitle": "Accurate structure prediction of biomolecular interactions with AlphaFold 3",
    "authors": [
      "Josh Abramson",
      "Jonas Adler",
      "Jack Dunger",
      "Richard Evans",
      "Tim Green",
      "Alexander Pritzel",
      "Olaf Ronneberger",
      "Lindsay Willmore",
      "Andrew J. Ballard",
      "Joshua Bambrick",
      "Sebastian W. Bodenstein",
      "David A. Evans",
      "Chia-Chun Hung",
      "Michael O'Neill",
      "David Reiman",
      "Kathryn Tunyasuvunakool",
      "Zachary Wu",
      "Akvilė Žemgulytė",
      "Eirini Arvaniti",
      "Charles Beattie",
      "Ottavia Bertolli",
      "Alex Bridgland",
      "Alexey Cherepanov",
      "Miles Congreve",
      "Alexander I. Cowen-Rivers",
      "Andrew Cowie",
      "Michael Figurnov",
      "Fabian B. Fuchs",
      "Hannah Gladman",
      "Rishub Jain",
      "Yousuf A. Khan",
      "Caroline M. R. Low",
      "Kuba Perlin",
      "Anna Potapenko",
      "Pascal Savy",
      "Sukhdeep Singh",
      "Adrian Stecula",
      "Ashok Thillaisundaram",
      "Catherine Tong",
      "Sergei Yakneen",
      "Ellen D. Zhong",
      "Michal Zielinski",
      "Augustin Žídek",
      "Victor Bapst",
      "Pushmeet Kohli",
      "Max Jaderberg",
      "Demis Hassabis",
      "John M. Jumper"
    ],
    "year": 2024,
    "venue": "Nature",
    "doi": "10.1038/s41586-024-07487-w",
    "url": "https://www.nature.com/articles/s41586-024-07487-w",
    "arxiv": null,
    "topics": [
      "foundation-models",
      "protein-structure"
    ],
    "articles": [
      "beyond-structure-prediction"
    ],
    "demo": true,
    "summaries": {
      "zh": "一种统一预测包含蛋白质、核酸、小分子、离子和修饰残基的复合物结构的方法。",
      "en": "A unified approach to predicting structures of complexes containing proteins, nucleic acids, small molecules, ions, and modified residues."
    }
  },
  {
    "slug": "scgpt",
    "originalTitle": "scGPT: toward building a foundation model for single-cell multi-omics using generative AI",
    "authors": [
      "Haotian Cui",
      "Chloe Wang",
      "Hassaan Maan",
      "Bo Wang"
    ],
    "year": 2024,
    "venue": "Nature Methods",
    "doi": "10.1038/s41592-024-02201-0",
    "url": "https://www.nature.com/articles/s41592-024-02201-0",
    "arxiv": "2302.08091",
    "topics": [
      "foundation-models",
      "single-cell"
    ],
    "articles": [
      "how-to-read-ai-bio-paper"
    ],
    "demo": true,
    "summaries": {
      "zh": "面向单细胞多组学数据的生成式预训练基础模型，并在多种下游任务上进行评估。",
      "en": "A generatively pretrained foundation model for single-cell multi-omics, evaluated across a range of downstream tasks."
    }
  }
] satisfies PaperRecord[];
export const topics = [
  {
    "slug": "foundation-models",
    "zh": "基础模型",
    "en": "Foundation models",
    "descriptionZh": "从预训练表征到生成式生物学。",
    "descriptionEn": "From pretrained representations to generative biology."
  },
  {
    "slug": "protein-structure",
    "zh": "蛋白质结构",
    "en": "Protein structure",
    "descriptionZh": "结构、相互作用与分子设计。",
    "descriptionEn": "Structure, interaction, and molecular design."
  },
  {
    "slug": "single-cell",
    "zh": "单细胞",
    "en": "Single-cell",
    "descriptionZh": "细胞图谱、扰动与多组学建模。",
    "descriptionEn": "Cell atlases, perturbations, and multi-omics modelling."
  },
  {
    "slug": "research-methods",
    "zh": "研究方法",
    "en": "Research methods",
    "descriptionZh": "严谨阅读、评估与复现。",
    "descriptionEn": "Rigorous reading, evaluation, and reproduction."
  },
  {
    "slug": "nucleic-acids",
    "zh": "核酸",
    "en": "Nucleic acids",
    "descriptionZh": "DNA、RNA、序列搜索与结构信息。",
    "descriptionEn": "DNA, RNA, sequence search, and structural information."
  }
] satisfies TopicRecord[];
