/* This file is generated by scripts/generate-content.mjs. */
import type { ComponentType } from 'react';
import Article0Zh from './generated/articles/beyond-structure-prediction.zh';
import Article0En from './generated/articles/beyond-structure-prediction.en';
import Article1Zh from './generated/articles/how-to-read-ai-bio-paper.zh';
import Article1En from './generated/articles/how-to-read-ai-bio-paper.en';

export const articleBodies: Record<string, Record<'zh' | 'en', ComponentType<Record<string, unknown>>>> = {
  "beyond-structure-prediction": { zh: Article0Zh, en: Article0En },
  "how-to-read-ai-bio-paper": { zh: Article1Zh, en: Article1En },
};
