/* This file is generated by scripts/generate-content.mjs. */
import type { ArticleRecord, PaperRecord, TopicRecord } from './types';
export const articles = [
  {
    "slug": "riboseek-fast-nucleotide-alignment",
    "topics": [
      "nucleic-acids"
    ],
    "papers": [
      "riboseek"
    ],
    "draft": false,
    "translations": {
      "zh": {
        "title": "Riboseek：加速核酸远缘同源搜索",
        "readingMinutes": 14
      },
      "en": {
        "title": "Riboseek: accelerating remote nucleotide homology search",
        "readingMinutes": 14
      }
    },
    "toc": {
      "zh": [
        {
          "id": "rna-结构预测的瓶颈常常发生在模型之前",
          "title": "RNA 结构预测的瓶颈，常常发生在模型之前",
          "level": 2
        },
        {
          "id": "riboseek-的核心用二联体保留局部上下文",
          "title": "Riboseek 的核心：用二联体保留局部上下文",
          "level": 2
        },
        {
          "id": "如何把查询序列变成可搜索的-profile",
          "title": "如何把查询序列变成可搜索的 profile？",
          "level": 3
        },
        {
          "id": "riboseek-如何在数据库中搜索",
          "title": "Riboseek 如何在数据库中搜索？",
          "level": 3
        },
        {
          "id": "搜索有多灵敏生成的比对有多可靠",
          "title": "搜索有多灵敏，生成的比对有多可靠？",
          "level": 2
        },
        {
          "id": "1-远缘同源检出能力与搜索速度",
          "title": "1. 远缘同源检出能力与搜索速度",
          "level": 3
        },
        {
          "id": "2-msa-能否保留二级结构信号",
          "title": "2. MSA 能否保留二级结构信号？",
          "level": 3
        },
        {
          "id": "173-万份预计算-rna-msa",
          "title": "173 万份预计算 RNA MSA",
          "level": 2
        },
        {
          "id": "如何看待-riboseek-的贡献与局限",
          "title": "如何看待 Riboseek 的贡献与局限？",
          "level": 2
        }
      ],
      "en": [
        {
          "id": "the-bottleneck-often-comes-before-model-inference",
          "title": "The bottleneck often comes before model inference",
          "level": 2
        },
        {
          "id": "riboseeks-core-preserving-local-context-with-di-mers",
          "title": "Riboseek's core: preserving local context with di-mers",
          "level": 2
        },
        {
          "id": "how-does-a-query-become-a-searchable-profile",
          "title": "How does a query become a searchable profile?",
          "level": 3
        },
        {
          "id": "how-does-riboseek-search-a-database",
          "title": "How does Riboseek search a database?",
          "level": 3
        },
        {
          "id": "how-sensitive-is-the-search-and-how-reliable-are-the-alignments",
          "title": "How sensitive is the search, and how reliable are the alignments?",
          "level": 2
        },
        {
          "id": "1-remote-homology-detection-and-search-speed",
          "title": "1. Remote-homology detection and search speed",
          "level": 3
        },
        {
          "id": "2-do-the-msas-preserve-secondary-structure-signals",
          "title": "2. Do the MSAs preserve secondary-structure signals?",
          "level": 3
        },
        {
          "id": "173-million-precomputed-rna-msas",
          "title": "1.73 million precomputed RNA MSAs",
          "level": 2
        },
        {
          "id": "strengths-and-limitations",
          "title": "Strengths and limitations",
          "level": 2
        }
      ]
    }
  }
] satisfies ArticleRecord[];
export const papers = [
  {
    "slug": "riboseek",
    "originalTitle": "Fast remote nucleotide sequence alignment with Riboseek",
    "authors": [
      "Sukhwan Park",
      "Kieran Didi",
      "Andrew Favor",
      "Anton Bushuiev",
      "Soohyun Kim",
      "Milot Mirdita",
      "Martin Steinegger"
    ],
    "year": 2026,
    "venue": "bioRxiv",
    "doi": "10.64898/2026.07.31.741718",
    "url": "https://www.biorxiv.org/content/10.64898/2026.07.31.741718v1.full",
    "arxiv": null,
    "topics": [
      "nucleic-acids"
    ],
    "articles": [
      "riboseek-fast-nucleotide-alignment"
    ],
    "summaries": {
      "zh": "Riboseek 用重叠二联体、快速预筛选和迭代 profile search 加速 RNA 与 DNA 的远缘同源搜索，并为 RNA 结构预测生成更深的多序列比对。",
      "en": "Riboseek accelerates remote homology search for RNA and DNA with overlapping di-mers, fast prefiltering, and iterative profile search, generating deeper MSAs for RNA structure prediction."
    }
  },
  {
    "slug": "melo",
    "originalTitle": "Measuring and locating the changes in protein structure using MELO",
    "authors": [
      "Lingyan Zheng",
      "Yang Liao",
      "Yintao Zhang",
      "Mingxuan Liu",
      "Mingkun Lu",
      "Tingting Fu",
      "Shuiyang Shi",
      "Xiuna Sun",
      "Chengbin Gu",
      "Huaicheng Sun",
      "Minjie Mou",
      "Haibin Dai",
      "Feng Zhu"
    ],
    "year": 2026,
    "venue": "Nature Communications",
    "doi": "10.1038/s41467-025-68110-8",
    "url": "https://www.nature.com/articles/s41467-025-68110-8",
    "arxiv": null,
    "topics": [
      "protein-structure"
    ],
    "articles": [],
    "summaries": {
      "zh": "MELO 从残基几何特征和残基间相对距离两个维度测量蛋白质结构变化，并定位二级结构变化与蛋白片段位移。",
      "en": "MELO measures protein structural change from residue geometry and relative inter-residue distances, while locating secondary-structure variation and protein-segment shifts."
    }
  },
  {
    "slug": "alphafold-3",
    "originalTitle": "Accurate structure prediction of biomolecular interactions with AlphaFold 3",
    "authors": [
      "Josh Abramson",
      "Jonas Adler",
      "Jack Dunger",
      "Richard Evans",
      "Tim Green",
      "Alexander Pritzel",
      "Olaf Ronneberger",
      "Lindsay Willmore",
      "Andrew J. Ballard",
      "Joshua Bambrick",
      "Sebastian W. Bodenstein",
      "David A. Evans",
      "Chia-Chun Hung",
      "Michael O'Neill",
      "David Reiman",
      "Kathryn Tunyasuvunakool",
      "Zachary Wu",
      "Akvilė Žemgulytė",
      "Eirini Arvaniti",
      "Charles Beattie",
      "Ottavia Bertolli",
      "Alex Bridgland",
      "Alexey Cherepanov",
      "Miles Congreve",
      "Alexander I. Cowen-Rivers",
      "Andrew Cowie",
      "Michael Figurnov",
      "Fabian B. Fuchs",
      "Hannah Gladman",
      "Rishub Jain",
      "Yousuf A. Khan",
      "Caroline M. R. Low",
      "Kuba Perlin",
      "Anna Potapenko",
      "Pascal Savy",
      "Sukhdeep Singh",
      "Adrian Stecula",
      "Ashok Thillaisundaram",
      "Catherine Tong",
      "Sergei Yakneen",
      "Ellen D. Zhong",
      "Michal Zielinski",
      "Augustin Žídek",
      "Victor Bapst",
      "Pushmeet Kohli",
      "Max Jaderberg",
      "Demis Hassabis",
      "John M. Jumper"
    ],
    "year": 2024,
    "venue": "Nature",
    "doi": "10.1038/s41586-024-07487-w",
    "url": "https://www.nature.com/articles/s41586-024-07487-w",
    "arxiv": null,
    "topics": [
      "foundation-models",
      "protein-structure"
    ],
    "articles": [],
    "summaries": {
      "zh": "一种统一预测包含蛋白质、核酸、小分子、离子和修饰残基的复合物结构的方法。",
      "en": "A unified approach to predicting structures of complexes containing proteins, nucleic acids, small molecules, ions, and modified residues."
    }
  },
  {
    "slug": "scgpt",
    "originalTitle": "scGPT: toward building a foundation model for single-cell multi-omics using generative AI",
    "authors": [
      "Haotian Cui",
      "Chloe Wang",
      "Hassaan Maan",
      "Bo Wang"
    ],
    "year": 2024,
    "venue": "Nature Methods",
    "doi": "10.1038/s41592-024-02201-0",
    "url": "https://www.nature.com/articles/s41592-024-02201-0",
    "arxiv": "2302.08091",
    "topics": [
      "foundation-models",
      "single-cell"
    ],
    "articles": [],
    "summaries": {
      "zh": "面向单细胞多组学数据的生成式预训练基础模型，并在多种下游任务上进行评估。",
      "en": "A generatively pretrained foundation model for single-cell multi-omics, evaluated across a range of downstream tasks."
    }
  }
] satisfies PaperRecord[];
export const topics = [
  {
    "slug": "foundation-models",
    "zh": "基础模型",
    "en": "Foundation models",
    "descriptionZh": "从预训练表征到生成式生物学。",
    "descriptionEn": "From pretrained representations to generative biology."
  },
  {
    "slug": "protein-structure",
    "zh": "蛋白质结构",
    "en": "Protein structure",
    "descriptionZh": "结构、相互作用与分子设计。",
    "descriptionEn": "Structure, interaction, and molecular design."
  },
  {
    "slug": "single-cell",
    "zh": "单细胞",
    "en": "Single-cell",
    "descriptionZh": "细胞图谱、扰动与多组学建模。",
    "descriptionEn": "Cell atlases, perturbations, and multi-omics modelling."
  },
  {
    "slug": "nucleic-acids",
    "zh": "核酸",
    "en": "Nucleic acids",
    "descriptionZh": "DNA、RNA、序列搜索与结构信息。",
    "descriptionEn": "DNA, RNA, sequence search, and structural information."
  }
] satisfies TopicRecord[];
