/* This file is generated by scripts/generate-content.mjs. */
import type { ArticleRecord, TopicRecord } from './types';
export const articles = [
  {
    "slug": "riboseek-fast-nucleotide-alignment",
    "topics": [
      "nucleic-acids"
    ],
    "draft": false,
    "cover": "public/images/riboseek/cover.jpg",
    "translations": {
      "zh": {
        "title": "Riboseek：加速核酸远缘同源搜索"
      },
      "en": {
        "title": "Riboseek: accelerating remote nucleotide homology search"
      }
    },
    "toc": {
      "zh": [
        {
          "id": "rna-结构预测的瓶颈常常发生在模型之前",
          "title": "RNA 结构预测的瓶颈，常常发生在模型之前",
          "level": 2
        },
        {
          "id": "riboseek-的核心用二联体保留局部上下文",
          "title": "Riboseek 的核心：用二联体保留局部上下文",
          "level": 2
        },
        {
          "id": "如何把查询序列变成可搜索的-profile",
          "title": "如何把查询序列变成可搜索的 profile？",
          "level": 3
        },
        {
          "id": "riboseek-如何在数据库中搜索",
          "title": "Riboseek 如何在数据库中搜索？",
          "level": 3
        },
        {
          "id": "搜索有多灵敏生成的比对有多可靠",
          "title": "搜索有多灵敏，生成的比对有多可靠？",
          "level": 2
        },
        {
          "id": "1-远缘同源检出能力与搜索速度",
          "title": "1. 远缘同源检出能力与搜索速度",
          "level": 3
        },
        {
          "id": "2-msa-能否保留二级结构信号",
          "title": "2. MSA 能否保留二级结构信号？",
          "level": 3
        },
        {
          "id": "173-万份预计算-rna-msa",
          "title": "173 万份预计算 RNA MSA",
          "level": 2
        },
        {
          "id": "如何看待-riboseek-的贡献与局限",
          "title": "如何看待 Riboseek 的贡献与局限？",
          "level": 2
        }
      ],
      "en": [
        {
          "id": "the-bottleneck-often-comes-before-model-inference",
          "title": "The bottleneck often comes before model inference",
          "level": 2
        },
        {
          "id": "riboseeks-core-preserving-local-context-with-di-mers",
          "title": "Riboseek's core: preserving local context with di-mers",
          "level": 2
        },
        {
          "id": "how-does-a-query-become-a-searchable-profile",
          "title": "How does a query become a searchable profile?",
          "level": 3
        },
        {
          "id": "how-does-riboseek-search-a-database",
          "title": "How does Riboseek search a database?",
          "level": 3
        },
        {
          "id": "how-sensitive-is-the-search-and-how-reliable-are-the-alignments",
          "title": "How sensitive is the search, and how reliable are the alignments?",
          "level": 2
        },
        {
          "id": "1-remote-homology-detection-and-search-speed",
          "title": "1. Remote-homology detection and search speed",
          "level": 3
        },
        {
          "id": "2-do-the-msas-preserve-secondary-structure-signals",
          "title": "2. Do the MSAs preserve secondary-structure signals?",
          "level": 3
        },
        {
          "id": "173-million-precomputed-rna-msas",
          "title": "1.73 million precomputed RNA MSAs",
          "level": 2
        },
        {
          "id": "strengths-and-limitations",
          "title": "Strengths and limitations",
          "level": 2
        }
      ]
    }
  }
] satisfies ArticleRecord[];
export const topics = [
  {
    "slug": "nucleic-acids",
    "zh": "核酸",
    "en": "Nucleic acids"
  }
] satisfies TopicRecord[];
